apiVersion: apps/v1
kind: Deployment
metadata:
   name: dotnet-app-deployment
spec:
   replicas: 3
   selector:
     matchLabels:
      app: dotnet-app-pod
   template:
    metadata:
     labels:
      app: dotnet-app-pod
    spec:
     containers:
      name: dotnet-app-container
      image: bhavinibatra/nagp-devops-demo:latest
     ports:
      name: http
      containerPort: 80
      protocol: TCP
 
apiVersion: v1
kind: Service
metadata:
 name: dotnet-app-service
spec:
 type: NodePort
 selector:
  app: dotnet-app-pod
 ports:
 - port: 80
   nodePort: 30159
   targetPort: 80 